# Generated by Django 4.0.4 on 2022-04-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='api.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelog',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='api.project'),
            preserve_default=False,
        ),
    ]
