# Generated by Django 4.0.4 on 2022-04-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timelog_client_timelog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
